name: allagash
channels:
  - defaults
dependencies:
  - python>=3.7
  - pandas>=1.0.5, <1.2.0
  - xlrd>=1.2.0
  - pulp>=2.4
  - conda-forge::coincbc>=2.9.8
  - geopandas>=0.8.1
  - matplotlib-base>=3.2.2
  - shapely>=1.6.4
  - requests>=2.24.0
  - ipykernel>=5.5.5
  - descartes>=1.1.0
  - pandoc>=2.2.3.2
  - pytest>=5.4.2
  - setuptools>=41.0.1
  - twine>=2.0.0
  - pip>=20.0.2
  - sphinx>=3.0.3
  - sphinx_rtd_theme>=0.4.3
  - conda-forge::nbsphinx>=0.4.2
  - conda-forge::nbval>=0.9.6
  - esri::arcgis>=1.8.2
  - pip:
    - allagash==0.2.1
    - pyzipcode~=3.0.1
